load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
# TB，   
    name = "SwiftEntryKit",
    module_name = "SwiftEntryKit",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
        #"-warnings-as-errors",
    ],
    deps = [
    ],
    visibility = [
        "//visibility:public",
    ],
)

#{
#  "name": "JXSegmentedView",
#  "version": "1.3.0",
#  "summary": "、、",
#  "homepage": "https://github.com/pujiaxin33/JXSegmentedView",
#  "license": "MIT",
#  "authors": {
#    "pujiaxin33": "317437084@qq.com"
#  },
#  "platforms": {
#    "ios": "9.0"
#  },
#  "swift_versions": "5.0",
#  "source": {
#    "git": "https://github.com/pujiaxin33/JXSegmentedView.git",
#    "tag": "1.3.0"
#  },
#  "frameworks": "UIKit",
#  "source_files": [
#    "Sources",
#    "Sources/**/*.{swift}"
#  ],
#  "requires_arc": true,
#  "swift_version": "5.0"
#}
