load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "TBTrack",
    module_name = "TBTrack",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
        #"-warnings-as-errors",
    ],
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit",
        "//TBModules/TBStorage:TBStorage",
        "//TBModules/TBNetwork:TBNetwork",
    ],
    visibility = [
        "//visibility:public",
    ],
)
